update=08/08/2017 12:50:59
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/gamaya
LibName31=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-Amphenol
LibName32=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-AnalogDevices
LibName33=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-back-up
LibName34=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-buffer
LibName35=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-device
LibName36=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-diode
LibName37=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-eBee_edison_version-rescue
LibName38=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-Edison
LibName39=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-ESDprotection
LibName40=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-ftdi
LibName41=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-G.Bee MB V0.0-cache
LibName42=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-Hamamatsu
LibName43=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-Hirose
LibName44=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-leds
LibName45=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-Lemo
LibName46=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-maxim
LibName47=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-microchip
LibName48=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-molex
LibName49=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-mosfet
LibName50=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-nxp
LibName51=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-OperationalAmplifier
LibName52=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-power
LibName53=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-quartz
LibName54=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-sd_card
LibName55=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-sensors
LibName56=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-SMA
LibName57=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-STMicroelectronic
LibName58=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-TEconnectivity(PIcamera)
LibName59=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-texas
LibName60=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-transistors
LibName61=C:/Users/Antonin Graf/Documents/GitHub/G-KiCad-Lib/library/G-UsbConnector
